/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_CellStateIndication_H_
#define	_CellStateIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NotificationCellList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellStateIndication */
typedef struct CellStateIndication {
	NotificationCellList_t	 notificationCellList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellStateIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellStateIndication;
extern asn_SEQUENCE_specifics_t asn_SPC_CellStateIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_CellStateIndication_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _CellStateIndication_H_ */
#include <asn_internal.h>
