/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_CellLoadReportingResponse_H_
#define	_CellLoadReportingResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EUTRANcellLoadReportingResponse.h"
#include <OCTET_STRING.h>
#include "EHRPDSectorLoadReportingResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellLoadReportingResponse_PR {
	CellLoadReportingResponse_PR_NOTHING,	/* No components present */
	CellLoadReportingResponse_PR_eUTRAN,
	CellLoadReportingResponse_PR_uTRAN,
	CellLoadReportingResponse_PR_gERAN,
	/* Extensions may appear below */
	CellLoadReportingResponse_PR_eHRPD
} CellLoadReportingResponse_PR;

/* CellLoadReportingResponse */
typedef struct CellLoadReportingResponse {
	CellLoadReportingResponse_PR present;
	union CellLoadReportingResponse_u {
		EUTRANcellLoadReportingResponse_t	 eUTRAN;
		OCTET_STRING_t	 uTRAN;
		OCTET_STRING_t	 gERAN;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		EHRPDSectorLoadReportingResponse_t	 eHRPD;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellLoadReportingResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellLoadReportingResponse;
extern asn_CHOICE_specifics_t asn_SPC_CellLoadReportingResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_CellLoadReportingResponse_1[4];
extern asn_per_constraints_t asn_PER_type_CellLoadReportingResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CellLoadReportingResponse_H_ */
#include <asn_internal.h>
