/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_CompositeAvailableCapacityGroup_H_
#define	_CompositeAvailableCapacityGroup_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CompositeAvailableCapacityGroup */
typedef OCTET_STRING_t	 CompositeAvailableCapacityGroup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CompositeAvailableCapacityGroup;
asn_struct_free_f CompositeAvailableCapacityGroup_free;
asn_struct_print_f CompositeAvailableCapacityGroup_print;
asn_constr_check_f CompositeAvailableCapacityGroup_constraint;
ber_type_decoder_f CompositeAvailableCapacityGroup_decode_ber;
der_type_encoder_f CompositeAvailableCapacityGroup_encode_der;
xer_type_decoder_f CompositeAvailableCapacityGroup_decode_xer;
xer_type_encoder_f CompositeAvailableCapacityGroup_encode_xer;
per_type_decoder_f CompositeAvailableCapacityGroup_decode_uper;
per_type_encoder_f CompositeAvailableCapacityGroup_encode_uper;
per_type_decoder_f CompositeAvailableCapacityGroup_decode_aper;
per_type_encoder_f CompositeAvailableCapacityGroup_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CompositeAvailableCapacityGroup_H_ */
#include <asn_internal.h>
