/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_E_RABNotToBeModifiedListBearerModInd_H_
#define	_E_RABNotToBeModifiedListBearerModInd_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-IE-ContainerList.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E-RABNotToBeModifiedListBearerModInd */
typedef E_RAB_IE_ContainerList_1197P7_t	 E_RABNotToBeModifiedListBearerModInd_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_RABNotToBeModifiedListBearerModInd_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_RABNotToBeModifiedListBearerModInd;
asn_struct_free_f E_RABNotToBeModifiedListBearerModInd_free;
asn_struct_print_f E_RABNotToBeModifiedListBearerModInd_print;
asn_constr_check_f E_RABNotToBeModifiedListBearerModInd_constraint;
ber_type_decoder_f E_RABNotToBeModifiedListBearerModInd_decode_ber;
der_type_encoder_f E_RABNotToBeModifiedListBearerModInd_encode_der;
xer_type_decoder_f E_RABNotToBeModifiedListBearerModInd_decode_xer;
xer_type_encoder_f E_RABNotToBeModifiedListBearerModInd_encode_xer;
per_type_decoder_f E_RABNotToBeModifiedListBearerModInd_decode_uper;
per_type_encoder_f E_RABNotToBeModifiedListBearerModInd_encode_uper;
per_type_decoder_f E_RABNotToBeModifiedListBearerModInd_decode_aper;
per_type_encoder_f E_RABNotToBeModifiedListBearerModInd_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABNotToBeModifiedListBearerModInd_H_ */
#include <asn_internal.h>
