/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_EHRPDCapacityValue_H_
#define	_EHRPDCapacityValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EHRPDCapacityValue */
typedef long	 EHRPDCapacityValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EHRPDCapacityValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EHRPDCapacityValue;
asn_struct_free_f EHRPDCapacityValue_free;
asn_struct_print_f EHRPDCapacityValue_print;
asn_constr_check_f EHRPDCapacityValue_constraint;
ber_type_decoder_f EHRPDCapacityValue_decode_ber;
der_type_encoder_f EHRPDCapacityValue_encode_der;
xer_type_decoder_f EHRPDCapacityValue_decode_xer;
xer_type_encoder_f EHRPDCapacityValue_encode_xer;
per_type_decoder_f EHRPDCapacityValue_decode_uper;
per_type_encoder_f EHRPDCapacityValue_encode_uper;
per_type_decoder_f EHRPDCapacityValue_decode_aper;
per_type_encoder_f EHRPDCapacityValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EHRPDCapacityValue_H_ */
#include <asn_internal.h>
