/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_EHRPDSectorCapacityClassValue_H_
#define	_EHRPDSectorCapacityClassValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EHRPDSectorCapacityClassValue */
typedef long	 EHRPDSectorCapacityClassValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EHRPDSectorCapacityClassValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EHRPDSectorCapacityClassValue;
asn_struct_free_f EHRPDSectorCapacityClassValue_free;
asn_struct_print_f EHRPDSectorCapacityClassValue_print;
asn_constr_check_f EHRPDSectorCapacityClassValue_constraint;
ber_type_decoder_f EHRPDSectorCapacityClassValue_decode_ber;
der_type_encoder_f EHRPDSectorCapacityClassValue_encode_der;
xer_type_decoder_f EHRPDSectorCapacityClassValue_decode_xer;
xer_type_encoder_f EHRPDSectorCapacityClassValue_encode_xer;
per_type_decoder_f EHRPDSectorCapacityClassValue_decode_uper;
per_type_encoder_f EHRPDSectorCapacityClassValue_encode_uper;
per_type_decoder_f EHRPDSectorCapacityClassValue_decode_aper;
per_type_encoder_f EHRPDSectorCapacityClassValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EHRPDSectorCapacityClassValue_H_ */
#include <asn_internal.h>
