/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_EHRPDMultiSectorLoadReportingResponseItem_H_
#define	_EHRPDMultiSectorLoadReportingResponseItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EHRPD-Sector-ID.h"
#include "EHRPDSectorLoadReportingResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EHRPDMultiSectorLoadReportingResponseItem */
typedef struct EHRPDMultiSectorLoadReportingResponseItem {
	EHRPD_Sector_ID_t	 eHRPD_Sector_ID;
	EHRPDSectorLoadReportingResponse_t	 eHRPDSectorLoadReportingResponse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EHRPDMultiSectorLoadReportingResponseItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EHRPDMultiSectorLoadReportingResponseItem;
extern asn_SEQUENCE_specifics_t asn_SPC_EHRPDMultiSectorLoadReportingResponseItem_specs_1;
extern asn_TYPE_member_t asn_MBR_EHRPDMultiSectorLoadReportingResponseItem_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EHRPDMultiSectorLoadReportingResponseItem_H_ */
#include <asn_internal.h>
