/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "FailureEventReport.h"

asn_per_constraints_t asn_PER_type_FailureEventReport_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_FailureEventReport_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FailureEventReport, choice.tooEarlyInterRATHOReportFromEUTRAN),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TooEarlyInterRATHOReportReportFromEUTRAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tooEarlyInterRATHOReportFromEUTRAN"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_FailureEventReport_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* tooEarlyInterRATHOReportFromEUTRAN */
};
asn_CHOICE_specifics_t asn_SPC_FailureEventReport_specs_1 = {
	sizeof(struct FailureEventReport),
	offsetof(struct FailureEventReport, _asn_ctx),
	offsetof(struct FailureEventReport, present),
	sizeof(((struct FailureEventReport *)0)->present),
	asn_MAP_FailureEventReport_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_FailureEventReport = {
	"FailureEventReport",
	"FailureEventReport",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_FailureEventReport_constr_1, CHOICE_constraint },
	asn_MBR_FailureEventReport_1,
	1,	/* Elements count */
	&asn_SPC_FailureEventReport_specs_1	/* Additional specs */
};

