/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_FailureEventReportingCause_H_
#define	_FailureEventReportingCause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FailureEventReportingCause {
	FailureEventReportingCause_application_container_syntax_error	= 0,
	FailureEventReportingCause_inconsistent_reporting_cell_identifier	= 1,
	FailureEventReportingCause_unspecified	= 2
	/*
	 * Enumeration is extensible
	 */
} e_FailureEventReportingCause;

/* FailureEventReportingCause */
typedef long	 FailureEventReportingCause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FailureEventReportingCause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FailureEventReportingCause;
extern const asn_INTEGER_specifics_t asn_SPC_FailureEventReportingCause_specs_1;
asn_struct_free_f FailureEventReportingCause_free;
asn_struct_print_f FailureEventReportingCause_print;
asn_constr_check_f FailureEventReportingCause_constraint;
ber_type_decoder_f FailureEventReportingCause_decode_ber;
der_type_encoder_f FailureEventReportingCause_encode_der;
xer_type_decoder_f FailureEventReportingCause_decode_xer;
xer_type_encoder_f FailureEventReportingCause_encode_xer;
per_type_decoder_f FailureEventReportingCause_decode_uper;
per_type_encoder_f FailureEventReportingCause_encode_uper;
per_type_decoder_f FailureEventReportingCause_decode_aper;
per_type_encoder_f FailureEventReportingCause_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FailureEventReportingCause_H_ */
#include <asn_internal.h>
