/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_FailureEventReport_H_
#define	_FailureEventReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TooEarlyInterRATHOReportReportFromEUTRAN.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FailureEventReport_PR {
	FailureEventReport_PR_NOTHING,	/* No components present */
	FailureEventReport_PR_tooEarlyInterRATHOReportFromEUTRAN
	/* Extensions may appear below */
	
} FailureEventReport_PR;

/* FailureEventReport */
typedef struct FailureEventReport {
	FailureEventReport_PR present;
	union FailureEventReport_u {
		TooEarlyInterRATHOReportReportFromEUTRAN_t	 tooEarlyInterRATHOReportFromEUTRAN;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FailureEventReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FailureEventReport;
extern asn_CHOICE_specifics_t asn_SPC_FailureEventReport_specs_1;
extern asn_TYPE_member_t asn_MBR_FailureEventReport_1[1];
extern asn_per_constraints_t asn_PER_type_FailureEventReport_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FailureEventReport_H_ */
#include <asn_internal.h>
