/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_IRAT_Cell_ID_H_
#define	_IRAT_Cell_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "EHRPD-Sector-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IRAT_Cell_ID_PR {
	IRAT_Cell_ID_PR_NOTHING,	/* No components present */
	IRAT_Cell_ID_PR_eUTRAN,
	IRAT_Cell_ID_PR_uTRAN,
	IRAT_Cell_ID_PR_gERAN,
	/* Extensions may appear below */
	IRAT_Cell_ID_PR_eHRPD
} IRAT_Cell_ID_PR;

/* IRAT-Cell-ID */
typedef struct IRAT_Cell_ID {
	IRAT_Cell_ID_PR present;
	union IRAT_Cell_ID_u {
		OCTET_STRING_t	 eUTRAN;
		OCTET_STRING_t	 uTRAN;
		OCTET_STRING_t	 gERAN;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		EHRPD_Sector_ID_t	 eHRPD;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IRAT_Cell_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IRAT_Cell_ID;
extern asn_CHOICE_specifics_t asn_SPC_IRAT_Cell_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_IRAT_Cell_ID_1[4];
extern asn_per_constraints_t asn_PER_type_IRAT_Cell_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IRAT_Cell_ID_H_ */
#include <asn_internal.h>
