/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_LPPa_PDU_H_
#define	_LPPa_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPPa-PDU */
typedef OCTET_STRING_t	 LPPa_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPPa_PDU;
asn_struct_free_f LPPa_PDU_free;
asn_struct_print_f LPPa_PDU_print;
asn_constr_check_f LPPa_PDU_constraint;
ber_type_decoder_f LPPa_PDU_decode_ber;
der_type_encoder_f LPPa_PDU_encode_der;
xer_type_decoder_f LPPa_PDU_decode_xer;
xer_type_encoder_f LPPa_PDU_encode_xer;
per_type_decoder_f LPPa_PDU_decode_uper;
per_type_encoder_f LPPa_PDU_encode_uper;
per_type_decoder_f LPPa_PDU_decode_aper;
per_type_encoder_f LPPa_PDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPPa_PDU_H_ */
#include <asn_internal.h>
