/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "MultiCellLoadReportingRequest.h"

asn_TYPE_member_t asn_MBR_MultiCellLoadReportingRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MultiCellLoadReportingRequest, requestedCellList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestedCellList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestedCellList"
		},
};
static const ber_tlv_tag_t asn_DEF_MultiCellLoadReportingRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MultiCellLoadReportingRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* requestedCellList */
};
asn_SEQUENCE_specifics_t asn_SPC_MultiCellLoadReportingRequest_specs_1 = {
	sizeof(struct MultiCellLoadReportingRequest),
	offsetof(struct MultiCellLoadReportingRequest, _asn_ctx),
	asn_MAP_MultiCellLoadReportingRequest_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MultiCellLoadReportingRequest = {
	"MultiCellLoadReportingRequest",
	"MultiCellLoadReportingRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_MultiCellLoadReportingRequest_tags_1,
	sizeof(asn_DEF_MultiCellLoadReportingRequest_tags_1)
		/sizeof(asn_DEF_MultiCellLoadReportingRequest_tags_1[0]), /* 1 */
	asn_DEF_MultiCellLoadReportingRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_MultiCellLoadReportingRequest_tags_1)
		/sizeof(asn_DEF_MultiCellLoadReportingRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MultiCellLoadReportingRequest_1,
	1,	/* Elements count */
	&asn_SPC_MultiCellLoadReportingRequest_specs_1	/* Additional specs */
};

