/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_MultiCellLoadReportingResponse_Item_H_
#define	_MultiCellLoadReportingResponse_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EUTRANResponse.h"
#include <OCTET_STRING.h>
#include "EHRPDMultiSectorLoadReportingResponseItem.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MultiCellLoadReportingResponse_Item_PR {
	MultiCellLoadReportingResponse_Item_PR_NOTHING,	/* No components present */
	MultiCellLoadReportingResponse_Item_PR_eUTRANResponse,
	MultiCellLoadReportingResponse_Item_PR_uTRANResponse,
	MultiCellLoadReportingResponse_Item_PR_gERANResponse,
	/* Extensions may appear below */
	MultiCellLoadReportingResponse_Item_PR_eHRPD
} MultiCellLoadReportingResponse_Item_PR;

/* MultiCellLoadReportingResponse-Item */
typedef struct MultiCellLoadReportingResponse_Item {
	MultiCellLoadReportingResponse_Item_PR present;
	union MultiCellLoadReportingResponse_Item_u {
		EUTRANResponse_t	 eUTRANResponse;
		OCTET_STRING_t	 uTRANResponse;
		OCTET_STRING_t	 gERANResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		EHRPDMultiSectorLoadReportingResponseItem_t	 eHRPD;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiCellLoadReportingResponse_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiCellLoadReportingResponse_Item;
extern asn_CHOICE_specifics_t asn_SPC_MultiCellLoadReportingResponse_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_MultiCellLoadReportingResponse_Item_1[4];
extern asn_per_constraints_t asn_PER_type_MultiCellLoadReportingResponse_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiCellLoadReportingResponse_Item_H_ */
#include <asn_internal.h>
