/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "MultiCellLoadReportingResponse-Item.h"

asn_per_constraints_t asn_PER_type_MultiCellLoadReportingResponse_Item_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_MultiCellLoadReportingResponse_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MultiCellLoadReportingResponse_Item, choice.eUTRANResponse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EUTRANResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eUTRANResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultiCellLoadReportingResponse_Item, choice.uTRANResponse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uTRANResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultiCellLoadReportingResponse_Item, choice.gERANResponse),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gERANResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultiCellLoadReportingResponse_Item, choice.eHRPD),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EHRPDMultiSectorLoadReportingResponseItem,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eHRPD"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MultiCellLoadReportingResponse_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eUTRANResponse */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uTRANResponse */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* gERANResponse */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* eHRPD */
};
asn_CHOICE_specifics_t asn_SPC_MultiCellLoadReportingResponse_Item_specs_1 = {
	sizeof(struct MultiCellLoadReportingResponse_Item),
	offsetof(struct MultiCellLoadReportingResponse_Item, _asn_ctx),
	offsetof(struct MultiCellLoadReportingResponse_Item, present),
	sizeof(((struct MultiCellLoadReportingResponse_Item *)0)->present),
	asn_MAP_MultiCellLoadReportingResponse_Item_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MultiCellLoadReportingResponse_Item = {
	"MultiCellLoadReportingResponse-Item",
	"MultiCellLoadReportingResponse-Item",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_MultiCellLoadReportingResponse_Item_constr_1, CHOICE_constraint },
	asn_MBR_MultiCellLoadReportingResponse_Item_1,
	4,	/* Elements count */
	&asn_SPC_MultiCellLoadReportingResponse_Item_specs_1	/* Additional specs */
};

