/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_NotifyFlag_H_
#define	_NotifyFlag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NotifyFlag {
	NotifyFlag_activated	= 0,
	NotifyFlag_deactivated	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NotifyFlag;

/* NotifyFlag */
typedef long	 NotifyFlag_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NotifyFlag_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NotifyFlag;
extern const asn_INTEGER_specifics_t asn_SPC_NotifyFlag_specs_1;
asn_struct_free_f NotifyFlag_free;
asn_struct_print_f NotifyFlag_print;
asn_constr_check_f NotifyFlag_constraint;
ber_type_decoder_f NotifyFlag_decode_ber;
der_type_encoder_f NotifyFlag_encode_der;
xer_type_decoder_f NotifyFlag_decode_xer;
xer_type_encoder_f NotifyFlag_encode_xer;
per_type_decoder_f NotifyFlag_decode_uper;
per_type_encoder_f NotifyFlag_encode_uper;
per_type_decoder_f NotifyFlag_decode_aper;
per_type_encoder_f NotifyFlag_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NotifyFlag_H_ */
#include <asn_internal.h>
