/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_NumberOfMeasurementReportingLevels_H_
#define	_NumberOfMeasurementReportingLevels_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NumberOfMeasurementReportingLevels {
	NumberOfMeasurementReportingLevels_rl2	= 0,
	NumberOfMeasurementReportingLevels_rl3	= 1,
	NumberOfMeasurementReportingLevels_rl4	= 2,
	NumberOfMeasurementReportingLevels_rl5	= 3,
	NumberOfMeasurementReportingLevels_rl10	= 4
	/*
	 * Enumeration is extensible
	 */
} e_NumberOfMeasurementReportingLevels;

/* NumberOfMeasurementReportingLevels */
typedef long	 NumberOfMeasurementReportingLevels_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NumberOfMeasurementReportingLevels_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NumberOfMeasurementReportingLevels;
extern const asn_INTEGER_specifics_t asn_SPC_NumberOfMeasurementReportingLevels_specs_1;
asn_struct_free_f NumberOfMeasurementReportingLevels_free;
asn_struct_print_f NumberOfMeasurementReportingLevels_print;
asn_constr_check_f NumberOfMeasurementReportingLevels_constraint;
ber_type_decoder_f NumberOfMeasurementReportingLevels_decode_ber;
der_type_encoder_f NumberOfMeasurementReportingLevels_encode_der;
xer_type_decoder_f NumberOfMeasurementReportingLevels_decode_xer;
xer_type_encoder_f NumberOfMeasurementReportingLevels_encode_xer;
per_type_decoder_f NumberOfMeasurementReportingLevels_decode_uper;
per_type_encoder_f NumberOfMeasurementReportingLevels_encode_uper;
per_type_decoder_f NumberOfMeasurementReportingLevels_decode_aper;
per_type_encoder_f NumberOfMeasurementReportingLevels_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfMeasurementReportingLevels_H_ */
#include <asn_internal.h>
