/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_ProtocolIE_ContainerList_H_
#define	_ProtocolIE_ContainerList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* ProtocolIE-ContainerList */
typedef struct ProtocolIE_ContainerList_7313P0 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P0_t;
typedef struct ProtocolIE_ContainerList_7313P1 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P1_t;
typedef struct ProtocolIE_ContainerList_7313P2 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P2_t;
typedef struct ProtocolIE_ContainerList_7313P3 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P3_t;
typedef struct ProtocolIE_ContainerList_7313P4 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P4_t;
typedef struct ProtocolIE_ContainerList_7313P5 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P5_t;
typedef struct ProtocolIE_ContainerList_7313P6 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P6_t;
typedef struct ProtocolIE_ContainerList_7313P7 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P7_t;
typedef struct ProtocolIE_ContainerList_7313P8 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P8_t;
typedef struct ProtocolIE_ContainerList_7313P9 {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_ContainerList_7313P9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ContainerList_7313P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_ContainerList_7313P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_ContainerList_7313P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ContainerList_7313P9_constr_19;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ContainerList_H_ */
#include <asn_internal.h>
