/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SonTransfer_IEs_MobilityInformation_H_
#define	_SonTransfer_IEs_MobilityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SonTransfer-IEs_MobilityInformation */
typedef BIT_STRING_t	 SonTransfer_IEs_MobilityInformation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SonTransfer_IEs_MobilityInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SonTransfer_IEs_MobilityInformation;
asn_struct_free_f SonTransfer_IEs_MobilityInformation_free;
asn_struct_print_f SonTransfer_IEs_MobilityInformation_print;
asn_constr_check_f SonTransfer_IEs_MobilityInformation_constraint;
ber_type_decoder_f SonTransfer_IEs_MobilityInformation_decode_ber;
der_type_encoder_f SonTransfer_IEs_MobilityInformation_encode_der;
xer_type_decoder_f SonTransfer_IEs_MobilityInformation_decode_xer;
xer_type_encoder_f SonTransfer_IEs_MobilityInformation_encode_xer;
per_type_decoder_f SonTransfer_IEs_MobilityInformation_decode_uper;
per_type_encoder_f SonTransfer_IEs_MobilityInformation_encode_uper;
per_type_decoder_f SonTransfer_IEs_MobilityInformation_decode_aper;
per_type_encoder_f SonTransfer_IEs_MobilityInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SonTransfer_IEs_MobilityInformation_H_ */
#include <asn_internal.h>
