/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SONtransferRequestContainer_H_
#define	_SONtransferRequestContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "MultiCellLoadReportingRequest.h"
#include "EventTriggeredCellLoadReportingRequest.h"
#include "HOReport.h"
#include "CellActivationRequest.h"
#include "CellStateIndication.h"
#include "FailureEventReport.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SONtransferRequestContainer_PR {
	SONtransferRequestContainer_PR_NOTHING,	/* No components present */
	SONtransferRequestContainer_PR_cellLoadReporting,
	/* Extensions may appear below */
	SONtransferRequestContainer_PR_multiCellLoadReporting,
	SONtransferRequestContainer_PR_eventTriggeredCellLoadReporting,
	SONtransferRequestContainer_PR_hOReporting,
	SONtransferRequestContainer_PR_eutranCellActivation,
	SONtransferRequestContainer_PR_energySavingsIndication,
	SONtransferRequestContainer_PR_failureEventReporting
} SONtransferRequestContainer_PR;

/* SONtransferRequestContainer */
typedef struct SONtransferRequestContainer {
	SONtransferRequestContainer_PR present;
	union SONtransferRequestContainer_u {
		NULL_t	 cellLoadReporting;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		MultiCellLoadReportingRequest_t	 multiCellLoadReporting;
		EventTriggeredCellLoadReportingRequest_t	 eventTriggeredCellLoadReporting;
		HOReport_t	 hOReporting;
		CellActivationRequest_t	 eutranCellActivation;
		CellStateIndication_t	 energySavingsIndication;
		FailureEventReport_t	 failureEventReporting;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SONtransferRequestContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SONtransferRequestContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _SONtransferRequestContainer_H_ */
#include <asn_internal.h>
