/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SONtransferResponseContainer_H_
#define	_SONtransferResponseContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellLoadReportingResponse.h"
#include "MultiCellLoadReportingResponse.h"
#include "EventTriggeredCellLoadReportingResponse.h"
#include <NULL.h>
#include "CellActivationResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SONtransferResponseContainer_PR {
	SONtransferResponseContainer_PR_NOTHING,	/* No components present */
	SONtransferResponseContainer_PR_cellLoadReporting,
	/* Extensions may appear below */
	SONtransferResponseContainer_PR_multiCellLoadReporting,
	SONtransferResponseContainer_PR_eventTriggeredCellLoadReporting,
	SONtransferResponseContainer_PR_hOReporting,
	SONtransferResponseContainer_PR_eutranCellActivation,
	SONtransferResponseContainer_PR_energySavingsIndication,
	SONtransferResponseContainer_PR_failureEventReporting
} SONtransferResponseContainer_PR;

/* SONtransferResponseContainer */
typedef struct SONtransferResponseContainer {
	SONtransferResponseContainer_PR present;
	union SONtransferResponseContainer_u {
		CellLoadReportingResponse_t	 cellLoadReporting;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		MultiCellLoadReportingResponse_t	 multiCellLoadReporting;
		EventTriggeredCellLoadReportingResponse_t	 eventTriggeredCellLoadReporting;
		NULL_t	 hOReporting;
		CellActivationResponse_t	 eutranCellActivation;
		NULL_t	 energySavingsIndication;
		NULL_t	 failureEventReporting;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SONtransferResponseContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SONtransferResponseContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _SONtransferResponseContainer_H_ */
#include <asn_internal.h>
