/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SONtransferApplicationIdentity_H_
#define	_SONtransferApplicationIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SONtransferApplicationIdentity {
	SONtransferApplicationIdentity_cell_load_reporting	= 0,
	/*
	 * Enumeration is extensible
	 */
	SONtransferApplicationIdentity_multi_cell_load_reporting	= 1,
	SONtransferApplicationIdentity_event_triggered_cell_load_reporting	= 2,
	SONtransferApplicationIdentity_ho_reporting	= 3,
	SONtransferApplicationIdentity_eutran_cell_activation	= 4,
	SONtransferApplicationIdentity_energy_savings_indication	= 5,
	SONtransferApplicationIdentity_failure_event_reporting	= 6
} e_SONtransferApplicationIdentity;

/* SONtransferApplicationIdentity */
typedef long	 SONtransferApplicationIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SONtransferApplicationIdentity;
asn_struct_free_f SONtransferApplicationIdentity_free;
asn_struct_print_f SONtransferApplicationIdentity_print;
asn_constr_check_f SONtransferApplicationIdentity_constraint;
ber_type_decoder_f SONtransferApplicationIdentity_decode_ber;
der_type_encoder_f SONtransferApplicationIdentity_encode_der;
xer_type_decoder_f SONtransferApplicationIdentity_decode_xer;
xer_type_encoder_f SONtransferApplicationIdentity_encode_xer;
per_type_decoder_f SONtransferApplicationIdentity_decode_uper;
per_type_encoder_f SONtransferApplicationIdentity_encode_uper;
per_type_decoder_f SONtransferApplicationIdentity_decode_aper;
per_type_encoder_f SONtransferApplicationIdentity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SONtransferApplicationIdentity_H_ */
#include <asn_internal.h>
