/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_TargetID_H_
#define	_TargetID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TargeteNB-ID.h"
#include "TargetRNC-ID.h"
#include "CGI.h"
#include "TargetNgRanNode-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TargetID_PR {
	TargetID_PR_NOTHING,	/* No components present */
	TargetID_PR_targeteNB_ID,
	TargetID_PR_targetRNC_ID,
	TargetID_PR_cGI,
	/* Extensions may appear below */
	TargetID_PR_targetgNgRanNode_ID
} TargetID_PR;

/* TargetID */
typedef struct TargetID {
	TargetID_PR present;
	union TargetID_u {
		TargeteNB_ID_t	 targeteNB_ID;
		TargetRNC_ID_t	 targetRNC_ID;
		CGI_t	 cGI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		TargetNgRanNode_ID_t	 targetgNgRanNode_ID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetID;
extern asn_CHOICE_specifics_t asn_SPC_TargetID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargetID_1[4];
extern asn_per_constraints_t asn_PER_type_TargetID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TargetID_H_ */
#include <asn_internal.h>
