/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_TooEarlyInterRATHOReportReportFromEUTRAN_H_
#define	_TooEarlyInterRATHOReportReportFromEUTRAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "SonTransfer-IEs_MobilityInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TooEarlyInterRATHOReportReportFromEUTRAN */
typedef struct TooEarlyInterRATHOReportReportFromEUTRAN {
	OCTET_STRING_t	 uERLFReportContainer;
	SonTransfer_IEs_MobilityInformation_t	*mobilityInformation;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TooEarlyInterRATHOReportReportFromEUTRAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TooEarlyInterRATHOReportReportFromEUTRAN;
extern asn_SEQUENCE_specifics_t asn_SPC_TooEarlyInterRATHOReportReportFromEUTRAN_specs_1;
extern asn_TYPE_member_t asn_MBR_TooEarlyInterRATHOReportReportFromEUTRAN_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TooEarlyInterRATHOReportReportFromEUTRAN_H_ */
#include <asn_internal.h>
