/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "s1ap.asn1"
 * 	`asn1c -D src -pdu=S1SetupRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_UEContextSuspendResponse_H_
#define	_UEContextSuspendResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEContextSuspendResponse */
typedef struct UEContextSuspendResponse {
	ProtocolIE_Container_7276P82_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEContextSuspendResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextSuspendResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_UEContextSuspendResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_UEContextSuspendResponse_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextSuspendResponse_H_ */
#include <asn_internal.h>
